yarnPath: .yarn/releases/yarn-3.6.3.cjs
nodeLinker: pnpm
packageExtensions:
  {
    "@stylexjs/babel-plugin@*":
      {
        dependencies:
          {
            "@babel/types": "^7.15.6",
            "postcss-value-parser": "^4.2.0",
            "invariant": "^2.2.4",
            "styleq": "^0.1.3",
            "@babel/traverse": "^7.0.0-0",
          },
      },
    "vite-imagetools@*": { dependencies: { "sharp": "0.32.6" } },
    "@remix-run/dev@*": { dependencies: { "isbot": "^3.6.8" } },
    "unplugin-vue-router@*":
      { dependencies: { "@vue/compiler-sfc": "^3.3.13" } },
    "@nuxt/vite-builder@*": { dependencies: { "ofetch": "^1.3.3" } },
    "waku@*":
      { dependencies: { "react-dom": "18.3.0-canary-1d5667a12-20240102" } },
  }
