// Manullay order
// For most of scence, we don't need to use this order, because the order will be generated by the stylex automatically.
// eg:
// import './index.css'; // Alouth the index.css is the first css file, but the order is not the first one for sometimes.
// import Component from './component'; // Component define with stylex.

// insert to the browser might be
// <style data-vite-dev-id="vite-plugin:stylex.css">...</style>
// <style data-vite-dev-id="index.css">...</style>
// We should ensure the right order by manually.

import type { RollupPluginContext } from './interface'

export async function ensureStyleOrder(id: string, stylexProcesser: () => string, pluginContext: RollupPluginContext) {
  // 
  const stylex = stylexProcesser()

  //   const r = await pluginContext.resolve(id)
  //   console.log(r, id)
  return stylex
}
